name: Setup jq
description: Simple GitHub Action to add jq to your path
inputs:
  version:
    description: Version of jq
    default: 1.6
outputs:
  path:
    description: Absolute path to the jq binary
    value: ${{ steps.jq.outputs.path }}
runs:
  using: composite
  steps:
    - shell: bash
      id: jq
      run: |
        if ${{ runner.os == 'Linux' }}; then
            bin_name=jq-linux64
            out_name=jq
            action_path_unix='${GITHUB_ACTION_PATH}'
        elif ${{ runner.os == 'Windows' }}; then
            bin_name=jq-win64.exe
            out_name=jq.exe
            action_path_unix=$(cygpath -u '${GITHUB_ACTION_PATH}')
            wget() { powershell -command "wget ${@}"; }
        elif ${{ runner.os == 'macOS' }}; then
            bin_name=jq-osx-amd64
            out_name=jq
            action_path_unix='${GITHUB_ACTION_PATH}'
        else
            exit 1
        fi
        mkdir ${action_path_unix}/jq
        curl -L \
          https://github.com/stedolan/jq/releases/download/jq-${{ inputs.version }}/${bin_name} \
          -o '${GITHUB_ACTION_PATH}'/jq/${out_name}
        chmod +x ${action_path_unix}/jq/${out_name}
        echo ${action_path_unix}/jq >> ${GITHUB_PATH}
        echo ::set-output name=path::'${{ github.action_path }}'/jq/${out_name}
